### ISSUE TITLE
E39 business radio 

### ISSUE THREAD

**Issue by zarboz** [ezeakeal/pyBus#5]
All text displays on my IKE instead of business radio head unit 
After a couple tracks the terminal shows ibus information but isn’t working any more 

I don’t know much about python but I’ll try to figure out what’s going on

**Comment by 3isenHeiM** [comment]
I guess it's a matter of address on the iBUS.
The address of the IKE on the E39 could be the same as the address of the Radio screen on the E46.

Have you tried googling for E39 iBUS codes ? [Quick find](http://www.danielbaratu.com/blog/2008/02/bmw-ibus-codes)...

I can then tell you how to change that address in the code to make it diplay on the right screen ;)

**Comment by zarboz** [comment]
@3isenHeiM  I got it hacked up and running but the way the text buffer on the radio or the MID center is different than the way it displays on the IKE

I kind of cleaned up the IKE stuff and set a code to clear the IKE display between displaying stuff so that i dont get wierd overlappinginformation

**Comment by zarboz** [comment]
So let me re iterate this problem now that I have read a lot about python and dissected what is going on from my terminal


at some point in the program it tries to run an unreferenced command and I cannot figure out what command it is looking for as it doesnt list the function just Main() not found and it dies

Will update issue with verbose logging output when i can capture it this evening

**Comment by zarboz** [comment]
2018/06/05T11:50:49 [DEBUG in pyBus_interface] READ: ['C8', '06', '80', ['23', '42', '32', '1E'], '03']
2018/06/05T11:50:49 [DEBUG in pyBus_eventDriver] MethodName (None) does not match a function
2018/06/05T11:50:49 [DEBUG in pyBus_interface] READ: ['18', '0A', '68', ['39', '02', '09', '00', '3F', '00', '01', '78'], '0E']
2018/06/05T11:50:49 [DEBUG in pyBus_eventDriver] MethodName (None) does not match a function
2018/06/05T11:50:49 [DEBUG in pyBus_interface] READ: ['68', '10', 'C0', ['23', 'C0', '20', '43', '44', '20', '31', '2D', '37', '38', '20', '20', '20', '20'], '4F']
2018/06/05T11:50:49 [DEBUG in pyBus_eventDriver] MethodName (None) does not match a function
2018/06/05T11:50:49 [DEBUG in pyBus_interface] READ: ['C8', '06', '80', ['23', '42', '32', '1E'], '03']
2018/06/05T11:50:49 [DEBUG in pyBus_eventDriver] MethodName (None) does not match a function
2018/06/05T11:50:49 [DEBUG in pyBus_interface] READ: ['C8', '06', '80', ['23', '42', '32', '1E'], '03']
2018/06/05T11:50:49 [DEBUG in pyBus_eventDriver] MethodName (None) does not match a function
2018/06/05T11:50:49 [DEBUG in pyBus_interface] READ: ['C0', '06', '68', ['31', '00', '00', '0D'], '92']
2018/06/05T11:50:49 [DEBUG in pyBus_eventDriver] MethodName (None) does not match a function
2018/06/05T11:50:49 [DEBUG in pyBus_interface] READ: ['68', '03', '18', ['01'], '72']
2018/06/05T11:50:49 [DEBUG in pyBus_eventDriver] Directive found for packet - d_cdPollResponse
2018/06/05T11:50:49 [DEBUG in pyBus_tickUtil] Enabling New Thread:
pollResponse {'COUNT': 0, 'INTERVAL': 30, 'THREAD': <_Timer(Thread-16, initial)>}
2018/06/05T11:50:49 [DEBUG in pyBus_interface] WRITE: Adding to stack: ['18', '04', 'FF', '02', '00']
2018/06/05T11:50:49 [DEBUG in pyBus_interface] WRITE: [24, 4, 255, 2, 0, 225]
2018/06/05T11:50:49 [DEBUG in pyBus_interface] WRITE: SUCCESS
2018/06/05T11:50:50 [DEBUG in pyBus_interface] WRITE: Adding to stack: ['68', '0B', 'c0', '21', '40', '00', '09', '05', '05', '4D', '50', '53']
2018/06/05T11:50:50 [DEBUG in pyBus_interface] WRITE: [104, 11, 192, 33, 64, 0, 9, 5, 5, 77, 80, 83, 133]
2018/06/05T11:50:50 [DEBUG in pyBus_interface] WRITE: SUCCESS
2018/06/05T11:50:50 [DEBUG in pyBus_interface] READ: ['C0', '06', '68', ['31', '00', '00', '4D'], 'D2']




Theres this problem right hree that pops up 2018/06/05T11:50:50 [DEBUG in pyBus_eventDriver] MethodName (None) does not match a function

anyway after I turn the car on and drive around the block the software will freeze as far as being able to control the pi from my steering wheel anymore and it continues to play songs until i turn the car off then . when back on its "no cd player/no tape"

**Comment by ezeakeal** [comment]
Hi there, I'm tied up with work at the moment, but will try review and see what the issue is. I remember coming across a similar issue a long time ago and fixing it.
I've since broke my crankshaft so had to lose the E46!
And thanks @3isenHeiM!!

**Comment by zarboz** [comment]
@ezeakeal  I appreciate that a ton man!

Update on behavior:

Started the car up today to run to the junk yard
Pi booted up got my Pybus welcome banner
CD starts playing a song.
I skipped a couple songs quickly till I found one I wanted to listen to
after about 2 minutes of song play I attempted to skip again
No response from the Pi
BUT the music was still playing
I got to the destination powered off my vehicle (btw the pi . doesnt shutdown when my car does)
got back in my car and powered back up and boom up pops CD player playing my song
still no control over the change track etc
after about 20 seconds of song play the Pi disconnects as "cd changer"

**Comment by ezeakeal** [comment]
I think I might rewrite this code tonight... 
There is probably room for improvement which might fix the issue.
Would also help me get more familiar with it.

What I recall is that the "CD EXISTS" message could get queued up for the ibus, but have too much of a backlog in front of it. So the message doesn't get sent quick enough and then the ibus thinks the CD drive is missing.
Maybe you have a particularly long track name getting queued up? If you have a really long string getting printed, it would queue up a lot of strings to emulate the text being scrolled across the display.
So "0 1 2 3 4 5 6 7 8 9" on a 6 character display might cause a queue like:
"0 1 2 3 4 5 6"
"1 2 3 4 5 6 7"
"2 3 4 5 6 7 8"
"3 4 5 6 7 8 9"
Then if the CD exist message is behind all of that, it doesn't get sent in time.
Pretty sure I tried solving that issue but wasn't satisfied with how it worked.
Will have a look at the code anyway.

Also, do you have a BMW rechargeable flashlight in your glovebox?
If so, that circuit is turned on when the car unlocks, and turns off after a delay when the car is locked.
I broke out the bulb and rammed a some thin cable in there, then powered a 12V USB hub from it.
I was able to plug the memory stick, a usb sound card, a wifi dongle, and the pi itself into the hub - worked a treat!

**Comment by zarboz** [comment]
@ezeakeal  Yeah i do have the flashlight in there I am waiting on my Mausberry to show up so I can run safe startup/shutdown process on the pi

I added a little bit to your code and made a pull request im not a total n00b but i sure don't know python

I have been trying to impliment similar changes in this other software I found that bridges Bluetooth->headunit but his software does not emulate the cd changer

i digress

I do have some longer titles but all are properly ID3 tagged items

**Comment by ezeakeal** [comment]
I'll check that pull request right away!

**Comment by zarboz** [comment]
Interesting development

Was at the junk yard today and found a cdb54 CD player off an x5 with an aux input !!!!!!

Got that for 30$ and installed right away 

Now I have aux input and a useless CD player up front 

I can still initialize pybus and it prints that I’m playing my song 

But I don’t get sound

Completely unrelated to this issue but thought I’d share ...

**Comment by zarboz** [comment]
@3isenHeiM  can you maybe help me out with the buffer?

I know my radio doesnt have a LCD because I have a 2000 E39 therefore my MID is technically the display for the radio


MID address is c0
i presume we can still use c8 (phone) as sender

shoot me an email im curious to learn more from you 

mugenman1111@gmail.com
